In [1]:
import pandas as pd
df1 = pd.read_csv("C:/Eversource Data/CT_MeasureData_Fall2020.csv")
df1.head()

,NU_ID,INSTALL_SELL_PAYMNT_AUTH_DT,PROGRAM_NAME,SUB_PROGRAM_NAME,UTILITY_COMPANY,SECTOR,END_USE,STATE,MEASURE_NAME,REFERENCE,MEASURE_REFERENCE_CODE,MEASURE_ID,MEASURE_LIFE_YEARS,COMMODITY,PROGRAM_YEAR
0,100053,30-NOV-14,Smart Living Catalog,Lighting Catalog,CLP,Residential,Lighting,CT,General LED Bulb,PSD,General LED Bulb,NaN,10.0,ELECTRIC,2014
1,100053,30-NOV-14,Smart Living Catalog,Lighting Catalog,CLP,Residential,Lighting,CT,Non General LED Bulb,PSD,Non General LED Bulb,NaN,10.0,ELECTRIC,2014
2,100054,31-JAN-15,Smart Living Catalog,Lighting Catalog,CLP,Residential,Lighting,CT,General Specialty CFL Bulb,PSD,General Specialty CFL Bulb,63215.0,4.0,ELECTRIC,2015
3,100054,31-JAN-15,Smart Living Catalog,Lighting Catalog,CLP,Residential,Lighting,CT,Non General Specialty CFL Bulb,PSD,Non General Specialty CFL Bulb,63214.0,4.0,ELECTRIC,2015
4,100055,31-JAN-15,Smart Living Catalog,Lighting Catalog,CLP,Residential,Lighting,CT,Non General LED Bulb,PSD,Non General LED Bulb,106569.0,10.0,ELECTRIC,2015

In [2]:
df2 = pd.read_csv("MA_MeasureData_Fall2020.csv",encoding='cp1252')
df2.head()

,NU_ID,YR,TRACKING_TYPE,LEGACY_PA_DNV,SITE_STATE_DNV,PROGRAM,END_USE_VERBOSE_DNV,BCR_DESCRIPTION_DNV,END_USE_IMPACTED_DNV,INSTALLATION_DATE_DNV,COMPLETE_DATE,VENDOR_INVOICE_DATE_DNV
0,740609,2013,E,NSTAR,MA,Retrofit,Industrial Processing | VSD | Variable Speed D...,NaN,PROCESS,NaN,NaN,NaN
1,559960,2015,E,NSTAR,MA,| Retrofit | | MOU | | | | | | |,LIGHTING | CUSTOM LIGHTING - 17 YEAR LIFE | CU...,NaN,LIGHTING,NaN,NaN,NaN
2,800656,2014,E,NSTAR,MA,NaN,Compressed Air | Compressed Air | Custom Compr...,NaN,COMPRESSED AIR,NaN,NaN,NaN
3,921083,2016,E,NSTAR,MA,C&I New Buildings & Major Renovations | CUSTOM...,HVAC | Custom - Comprehensive Design - 17 year...,NaN,COMPREHENSIVE DESIGN,NaN,21-JUL-16,NaN
4,740698,2013,E,NSTAR,MA,Retrofit,HVAC | Energy Management System | EMS Level 3:...,NaN,HVAC,NaN,NaN,NaN

In [3]:
data1 = df1.drop(columns = ['NU_ID','PROGRAM_NAME','SUB_PROGRAM_NAME','REFERENCE','MEASURE_ID','COMMODITY','INSTALL_SELL_PAYMNT_AUTH_DT','MEASURE_LIFE_YEARS','MEASURE_REFERENCE_CODE'],axis = 1)
d1=data1.rename(columns={'UTILITY_COMPANY':'Utility','MEASURE_NAME':'MeasureName', 'PROGRAM_YEAR':'YR'})
d1.astype(str)
d1.head()

  Utility       SECTOR   END_USE STATE                     MeasureName    YR
0     CLP  Residential  Lighting    CT                General LED Bulb  2014
1     CLP  Residential  Lighting    CT            Non General LED Bulb  2014
2     CLP  Residential  Lighting    CT      General Specialty CFL Bulb  2015
3     CLP  Residential  Lighting    CT  Non General Specialty CFL Bulb  2015
4     CLP  Residential  Lighting    CT            Non General LED Bulb  2015

In [4]:
d2=d1.copy()
d2['MeasureName'] = d2['SECTOR'] + ' ' + d2['END_USE'] +' ' + d2['MeasureName']
d2.head()

,Utility,SECTOR,END_USE,STATE,MeasureName,YR
0,CLP,Residential,Lighting,CT,Residential Lighting General LED Bulb,2014
1,CLP,Residential,Lighting,CT,Residential Lighting Non General LED Bulb,2014
2,CLP,Residential,Lighting,CT,Residential Lighting General Specialty CFL Bulb,2015
3,CLP,Residential,Lighting,CT,Residential Lighting Non General Specialty CFL...,2015
4,CLP,Residential,Lighting,CT,Residential Lighting Non General LED Bulb,2015

In [5]:
d2 = d2[['YR','Utility','STATE','MeasureName']]
d2.head()

     YR Utility STATE                                        MeasureName
0  2014     CLP    CT              Residential Lighting General LED Bulb
1  2014     CLP    CT          Residential Lighting Non General LED Bulb
2  2015     CLP    CT    Residential Lighting General Specialty CFL Bulb
3  2015     CLP    CT  Residential Lighting Non General Specialty CFL...
4  2015     CLP    CT          Residential Lighting Non General LED Bulb

In [6]:
data2 = df2.drop(columns=['NU_ID', 'TRACKING_TYPE', 'INSTALLATION_DATE_DNV', 'COMPLETE_DATE', 'VENDOR_INVOICE_DATE_DNV'])
data3 = data2.rename(columns={'LEGACY_PA_DNV':'Utility', 'PROGRAM_YEAR':'YR','SITE_STATE_DNV':'STATE','END_USE_IMPACTED_DNV':'END_USE','PROGRAM':'SECTOR'})
data3.head()

,YR,Utility,STATE,SECTOR,END_USE_VERBOSE_DNV,BCR_DESCRIPTION_DNV,END_USE
0,2013,NSTAR,MA,Retrofit,Industrial Processing | VSD | Variable Speed D...,NaN,PROCESS
1,2015,NSTAR,MA,| Retrofit | | MOU | | | | | | |,LIGHTING | CUSTOM LIGHTING - 17 YEAR LIFE | CU...,NaN,LIGHTING
2,2014,NSTAR,MA,NaN,Compressed Air | Compressed Air | Custom Compr...,NaN,COMPRESSED AIR
3,2016,NSTAR,MA,C&I New Buildings & Major Renovations | CUSTOM...,HVAC | Custom - Comprehensive Design - 17 year...,NaN,COMPREHENSIVE DESIGN
4,2013,NSTAR,MA,Retrofit,HVAC | Energy Management System | EMS Level 3:...,NaN,HVAC

In [7]:
data3.astype(str)

,YR,Utility,STATE,SECTOR,END_USE_VERBOSE_DNV,BCR_DESCRIPTION_DNV,END_USE
0,2013,NSTAR,MA,Retrofit,Industrial Processing | VSD | Variable Speed D...,nan,PROCESS
1,2015,NSTAR,MA,| Retrofit | | MOU | | | | | | |,LIGHTING | CUSTOM LIGHTING - 17 YEAR LIFE | CU...,nan,LIGHTING
2,2014,NSTAR,MA,nan,Compressed Air | Compressed Air | Custom Compr...,nan,COMPRESSED AIR
3,2016,NSTAR,MA,C&I New Buildings & Major Renovations | CUSTOM...,HVAC | Custom - Comprehensive Design - 17 year...,nan,COMPREHENSIVE DESIGN
4,2013,NSTAR,MA,Retrofit,HVAC | Energy Management System | EMS Level 3:...,nan,HVAC
...,...,...,...,...,...,...,...
2180907,2018,NSTAR,MA,Residential Products,LED FIXTURE (REFLECTORS) | . | LED | LED_FIXTU...,LED Fixture (Reflectors),LIGHTING
2180908,2018,WMECO,MA,Residential Products,LED BULB (SPECIALTY) | . | LED | BD_LED_EISA_1...,LED Bulb (Specialty),LIGHTING
2180909,2018,NSTAR,MA,Residential Products,LED BULB (REFLECTORS) | . | LED | LED_REFLECTO...,LED Bulb (Reflectors),LIGHTING
2180910,2018,NSTAR,MA,Residential Products,LED BULB | . | LED | BD_LED_BULB | BUY DOWN LE...,LED Bulb,LIGHTING
2180911,2018,NSTAR,MA,Residential Products,LED BULB (SPECIALTY) | . | LED | BD_LED_EISA_1...,LED Bulb (Specialty),LIGHTING

In [8]:
import numpy as np
data3 = data3.replace(np.nan, '', regex=True)

In [9]:
data3['MeasureName'] = data3['SECTOR'] + ' ' + data3['END_USE'] + ' '  + data3['END_USE_VERBOSE_DNV'] + ' ' + data3['BCR_DESCRIPTION_DNV']

In [10]:
data3.drop(columns=['END_USE_VERBOSE_DNV','BCR_DESCRIPTION_DNV'])
data3.head()

,YR,Utility,STATE,SECTOR,END_USE_VERBOSE_DNV,BCR_DESCRIPTION_DNV,END_USE,MeasureName
0,2013,NSTAR,MA,Retrofit,Industrial Processing | VSD | Variable Speed D...,,PROCESS,Retrofit PROCESS Industrial Processing | VSD |...
1,2015,NSTAR,MA,| Retrofit | | MOU | | | | | | |,LIGHTING | CUSTOM LIGHTING - 17 YEAR LIFE | CU...,,LIGHTING,| Retrofit | | MOU | | | | | | | LIGHTI...
2,2014,NSTAR,MA,,Compressed Air | Compressed Air | Custom Compr...,,COMPRESSED AIR,COMPRESSED AIR Compressed Air | Compressed Ai...
3,2016,NSTAR,MA,C&I New Buildings & Major Renovations | CUSTOM...,HVAC | Custom - Comprehensive Design - 17 year...,,COMPREHENSIVE DESIGN,C&I New Buildings & Major Renovations | CUSTOM...
4,2013,NSTAR,MA,Retrofit,HVAC | Energy Management System | EMS Level 3:...,,HVAC,Retrofit HVAC HVAC | Energy Management System ...

In [11]:
data3 = data3[['YR','Utility','STATE','MeasureName']]
data3.head()

     YR Utility STATE                                        MeasureName
0  2013   NSTAR    MA  Retrofit PROCESS Industrial Processing | VSD |...
1  2015   NSTAR    MA  | Retrofit |  | MOU |  |  |  |  |  |  | LIGHTI...
2  2014   NSTAR    MA   COMPRESSED AIR Compressed Air | Compressed Ai...
3  2016   NSTAR    MA  C&I New Buildings & Major Renovations | CUSTOM...
4  2013   NSTAR    MA  Retrofit HVAC HVAC | Energy Management System ...

In [12]:
final_data = pd.concat([d2, data3],ignore_index=True)
final_data.head()

     YR Utility STATE                                        MeasureName
0  2014     CLP    CT              Residential Lighting General LED Bulb
1  2014     CLP    CT          Residential Lighting Non General LED Bulb
2  2015     CLP    CT    Residential Lighting General Specialty CFL Bulb
3  2015     CLP    CT  Residential Lighting Non General Specialty CFL...
4  2015     CLP    CT          Residential Lighting Non General LED Bulb

In [13]:
final = pd.DataFrame(final_data)
final = final.sort_index()
final.MeasureName = final.MeasureName.astype(str)

In [14]:
# Apply a first round of text cleaning techniques
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

round1 = lambda x: clean_text_round1(x)

In [15]:
# Let's take a look at the updated text
data_clean = pd.DataFrame(final.MeasureName.apply(round1))
data_clean

                                               MeasureName
0                    residential lighting general led bulb
1                residential lighting non general led bulb
2          residential lighting general specialty cfl bulb
3        residential lighting non general specialty cfl...
4                residential lighting non general led bulb
...                                                    ...
4883502  residential products lighting led fixture refl...
4883503  residential products lighting led bulb special...
4883504  residential products lighting led bulb reflect...
4883505  residential products lighting led bulb    led ...
4883506  residential products lighting led bulb special...

[4883507 rows x 1 columns]

In [16]:
unique = data_clean.MeasureName.unique()
unique

array(['residential lighting general led bulb',
       'residential lighting non general led bulb',
       'residential lighting general specialty cfl bulb', ...,
       'ci retrofit lighting led fixture indoor common area    lighting  mfcommonintfixturesci  mfcommonintfixtures for mf ci meters  lighting  cree  downlight common  new led fixture indoor common area',
       'residential whole house envelope insulation other  insulationrebatew  insulation rebate for wood heated homess  hvac  attic floor enc cell dp   insulation insulation other',
       'ci retrofit lighting lighting systems  interior  high performance lighting  led fixture    led   driver lighting systems  interior'],
      dtype=object)

In [18]:
Names = pd.DataFrame(unique)

In [19]:
Names.to_csv('CleanedMeasureNames.csv')